### ISSUE TITLE
About camera intrinsics retrival for SFM

### ISSUE THREAD

**Issue by HyHuang1995** [dadung/G2D#1]
Impressing work! But it seems that you did not mention how the camera intrinsics were achieved from the game.

Are you simply feed an initial guess to the SFM framework and let the algorithm optimizes it, or calculate it from information like FOV achieved from the game?

**Comment by dzungdoan6** [comment]
Hello, thanks for your interest in G2D.
The video sequence extracted by G2D does not have camera intrinsics. I did exactly as what you said, let SfM optimize camera intrinsics (with "shared intrinsics" option)

**Comment by HyHuang1995** [comment]
Thank you for your reply. 

Maybe I will investigate automatic intrinsic exportation if I have time.

**Comment by NagabhushanSN95** [comment]
@HyHuang1995 were you able to extract camera intrinsic automatically?
