### ISSUE TITLE
Pose provided is Wrong?

### ISSUE THREAD

**Issue by Abrar3616** [dadung/G2D#10]
Hi, I am doing a fundamental matrix check on the images and poses provided by the code through epipolar lines, however when i check the epipolar lines they do not seem to pass through the selected object. The same check has been run on the Minos simulator and they provide accurate checks as the poses are also accurate. However on the poses provided here the check fails. As you can see the object i have selected in the first image is the railing on the left of the image and in the second image the epipolar line should pass through the same point in the railing but it doesn't. Please any help will be appreciated.
![3](https://user-images.githubusercontent.com/74458556/116373547-e2123600-a826-11eb-8f38-b7d51c7b3e69.jpg)
![3a](https://user-images.githubusercontent.com/74458556/116373551-e2aacc80-a826-11eb-80ce-85a36485f6a5.jpg)

**Comment by dzungdoan6** [comment]
Hi Abrar3616. So sorry for my late reply. 
To be honest, I haven't looked into poses from G2D in detail, hence I can't tell if they follow projective geometry :) 
My suggestion is to use COLMAP for 3D reconstruction and use its poses for your application. You can see in my technical report, when I align the poses from COLMAP and G2D, the alignment errors are very small. Hence, you can use G2D poses to guide image matching for COLMAP :)

**Comment by Abrar3616** [comment]
Alright thanks for your input
