### ISSUE TITLE
Real time Image Capture

### ISSUE THREAD

**Issue by Abrar3616** [dadung/G2D#11]
Hi again. I'm sorry for disturbing you so much, i wanted to ask you if there is some way to get images while playing the game i.e. Realtime. I tried your gdiscreencapture function but it just freezes the screen and then takes screen shots. i tried to take screenshots for 10 seconds but I am only getting multiple images of same frame as the game freezes on initialization of gdiscreencapture function. Please help.

**Comment by dzungdoan6** [comment]
Hi Abrar3616. Do you need to record camera pose of every frame? If not, maybe you can use NVIDIA ShadowPlay to record the video while playing the game: https://www.nvidia.com/en-us/geforce/geforce-experience/shadowplay/
You can find many tutorials on Youtube about NVIDIA ShadowPlay

**Comment by Abrar3616** [comment]
HI thanks for your reply. No i do not need poses. just the images at 10fps. Thankyou i will look into it and let you know.

**Comment by Abrar3616** [comment]
Thanks i used your method with multi-threading and it worked. Just one last question what can i do if i want to save the images in smaller size like 640x480. Your help will be greatly appreciated

**Comment by dzungdoan6** [comment]
Hi Abrar3616,
How about using OpenCV to resize images? (see [here](https://learnopencv.com/image-resizing-with-opencv/))

**Comment by Abrar3616** [comment]
Thanks Dadung 
I actually wanted to resize the images before saving but i guess I'll just resize them later.
