### ISSUE TITLE
Segmentation masks from GTA 5

### ISSUE THREAD

**Issue by HarshPathakhp** [dadung/G2D#3]
Hey, is it possible to extract segmentation masks for GTA 5 from G2D. I know its not written in the use cases but is it something that can be done by modifying the codebase?
Thanks

**Comment by dzungdoan6** [comment]
I think it is doable. I have an idea to implement but have no time.
You can use the code of gamehook here: https://github.com/philkr/gamehook
Basically, they intercept the DirectX to obtain the ground truth labels. I had a quick look through their code , I feel it is possible to integrate their code to my code.

**Comment by HarshPathakhp** [comment]
Yeah, I found their code shortly afterwards. Thank you for your response.
