### ISSUE TITLE
Free Cam Mod

### ISSUE THREAD

**Issue by hobincar** [dadung/G2D#4]
Thank you for releasing this amazing work!

One question. Can it be extended to collect frames captured in Mod like [Free Cam Mode](https://www.youtube.com/watch?v=xOumgXe7mDs) instead of the view of a running pedestrian?

**Comment by dzungdoan6** [comment]
Yes! It is doable, please have a look at function `void updateCamera(float coord_x, float coord_y, float coord_z, float rot_x, float rot_y, float rot_z)` in `TrajectoryTool/script.cpp`, there are two functions `CAM::SET_CAM_COORD` and `CAM::SET_CAM_ROT`, which meets your requirement.

In my implementation, there are two steps:
1. I leverage protagonist to obtain a list of 6 DoF camera poses
2. For each camera pose within the list, I assign the value of camera pose to the game camera.

Therefore, as long as you know 6 DoF camera poses, you can move the game camera.

**Comment by hobincar** [comment]
Thank you for your detailed explanation! It really helped a lot. 
I'll come back later if I have further question.
