### ISSUE TITLE
GTA 5 Game

### ISSUE THREAD

**Issue by Abrar3616** [dadung/G2D#5]
Hi this is more a question than an issue does the game need to be bought from steam or can this work for a cracked game? thanks

**Comment by dzungdoan6** [comment]
Hello! Thanks for your interest in G2D.

I haven't tried the cracked one, so I don't know if G2D works properly. G2D strongly depends on Scripthook, so if other mods developed using Scripthook could work, likely G2D works.

However,I strongly recommend you to buy GTA, now is the winter sale with about 60% discount, which makes GTA's cost is equivalent to few cups of coffee. Crack softwares usually contain viruses.

**Comment by Abrar3616** [comment]
Thanks for the clarification
