### ISSUE TITLE
Cant find Vertext.txt

### ISSUE THREAD

**Issue by Abrar3616** [dadung/G2D#6]
I am running a cracked version of gta5 and after creating the vertices using the tool i cant find the vertex.txt file in the gta5 directory. Both the weather and trajectory tool are working but the file cannot be found i dont know if it is even created. Could you please help me with this. Thanks

**Comment by dzungdoan6** [comment]
Hello! Can you please clarify "trajectory tool is working"? Creating vertex.txt is a function within trajectory tool.

When you place the marker on the map, then click `"Add vertex"`, does it show the notification `"Add vertex < coordinate X >, < coordinate Y >, < coordinate Z >"` on your game screen??

If you can't find a way to create "vertex.txt" with my code, please try to modify & recompile my code in this way
1. Find the parameter `_vertex_file_text` in file `G2D/TrajectoryTool/script.cpp`. There, I set: 
`std::string _vertex_file_text = "vertex.txt";`
2. Change the value of the parameter `_vertex_file_text` to the absolute path of your machine
3. Recompile the code

**Comment by Abrar3616** [comment]
Hi yes that notification shows. ill try to recompile and then let you know if it works

**Comment by Abrar3616** [comment]
I am getting the following error and am not able to add this include file as it does not recognize it.

1>------ Build started: Project: TrajectoryTool, Configuration: Release|Win32 ------
  dllmain.cpp
c:\users\hp\downloads\g2d-master\g2d-master\trajectorytool\dllmain.cpp(28): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
  keyboard.cpp
c:\users\hp\downloads\g2d-master\g2d-master\trajectorytool\keyboard.cpp(49): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
  script.cpp
c:\users\hp\downloads\g2d-master\g2d-master\trajectorytool\script.cpp(939): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by dzungdoan6** [comment]
How about you turn off the pre-compiled headers:
+ Go to ` Project Properties -> C++ -> Precompiled Headers`
+ Set ` Precompiled Header` to `Not Using Precompiled Header`

**Comment by Abrar3616** [comment]
i tried that but for some reason i cant access the project properties

**Comment by dzungdoan6** [comment]
To ensure my project code does not have any problem with configuration, could you please try to compile the `Native Trainer project` which comes with `ScriptHook V`? you can download it from `For developers` in this link: http://www.dev-c.com/gtav/scripthookv/
There are two possibilities:
1. If you could compile Native Trainer, it could mean my project code was wrongly configured 
2. If you couldn't compile Native Trainer, it could mean you are wrongly using Visual Studio version (or something like that)

**Comment by Abrar3616** [comment]
Which file should i compile in the project?

**Comment by dzungdoan6** [comment]
Please open `samples/NativeTrainer.sln` and compile it

**Comment by Abrar3616** [comment]
ok will let you know in a while visual studio is updating now

**Comment by Abrar3616** [comment]
Also just to clarify i changed the variables in script.cpp as you suggested now for compiling i should compile only script.cpp or some other file?

**Comment by Abrar3616** [comment]
After compiling your  project i am getting two of the following error:

Error	C1083	Cannot open include file: 'atlimage': No such file or directory  in script.h line 14

**Comment by Abrar3616** [comment]
After building native trainer, which is succesful i get the following popup

![image](https://user-images.githubusercontent.com/74458556/104907017-46129c00-59a6-11eb-8350-3095c8cea202.png)

**Comment by Abrar3616** [comment]
This is the final error i get after compiling your code:

Error	C1083	Cannot open include file: 'atlimage.h': No such file or directory	TrajectoryTool	c:\users\hp\downloads\g2d-master\g2d-master\trajectorytool\script.h	14

**Comment by dzungdoan6** [comment]
Probably you need to reinstall Visual Studio, "atlimage.h" belongs to default libaries of Microsoft C++

**Comment by Abrar3616** [comment]
Hey So i have built the solution successfully, your right the specific module was not selected while installing. However after changing the file path i still cant find the vertex.txt file.  i also copied the newly built .asi files from bin folder to my gta directory. i can use the condition tool and the trajectory tool shows the msg that vertex is added but i cant find the file in my specified directory as mentioned in the code.

![image](https://user-images.githubusercontent.com/74458556/106425723-24291700-6486-11eb-8fbc-77b221cd4ee0.png)

**Comment by dzungdoan6** [comment]
I see whitespace within your directory, which is probably the problem. 
A quick test is to create a folder `OutputG2D` within `C:/`, then put the directory `C:/OutputG2D`
Let's see how it is going.

**Comment by Abrar3616** [comment]
ok will try that

**Comment by Abrar3616** [comment]
I also this get this msg after i compile. can this be ignored?

![image](https://user-images.githubusercontent.com/74458556/106427741-b383f980-6489-11eb-8546-bfedde8d94dd.png)

**Comment by dzungdoan6** [comment]
Because you click `compile and run`, just click `compile`, you won't get that message

**Comment by Abrar3616** [comment]
Ok thanks, and the spaces was the issue  Now i can see the file

![image](https://user-images.githubusercontent.com/74458556/106428234-74a27380-648a-11eb-9b8a-5dcff88dfc6d.png)

**Comment by Abrar3616** [comment]
So can i just use this directory for the dataset images and all other files?

**Comment by dzungdoan6** [comment]
Probably you need to create `C:/OutputG2D/dataset` and `C:/OutputG2D/dataset/images`
And also update all corresponding parameters with `C:/OutputG2D`

P/S: I will close this thread. If you have other issue, please open another thread, because this thread's title is about "can't find vertex.txt" while you've found it. This helps other people easily search solutions that relate to their corresponding issues.

**Comment by Abrar3616** [comment]
Yes thankyou very much for your help
