### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by Abrar3616** [dadung/G2D#7]
Hi I would like to calibrate the gta5 camera that you have used for image extraction. I want to use the images for some other purpose for which i need the intrinsic parameters of the camera. Can you guide me, how i can get those features? Many Thanks

**Comment by Abrar3616** [comment]
Also could you tell me the fps of the camera

**Comment by dzungdoan6** [comment]
Hello
1. Currently, I haven't had a function to add checkerboard to the game for camera calibration. 
But we can use Structure from motion (e.g., COLMAP) to get a "bit noisy" intrinsic parameters. 
2. Fps is 60 frames/second

**Comment by Abrar3616** [comment]
Thanks Sorry for the late close.
