### ISSUE TITLE
Is it possible to extract depth maps?

### ISSUE THREAD

**Issue by NagabhushanSN95** [dadung/G2D#9]
Hi,

Thanks for the amazing work. Is it possible to extract depth maps (without using SFM)? If yes, can you please guide me on how to modify your code to do that?

**Comment by dzungdoan6** [comment]
Hi,

Thanks for your interest. The current version can't extract depth map, but it is a doable task.

My idea is to use [gamehook](https://github.com/philkr/gamehook)
In `G2D/TrajectoryTool/script.cpp`, you can see the function `GDITakeScreenshots()`, which is the function taking the screenshot. This function is used within the function `executeDenseTrajectory()`. I think we can develop your own function (using gamehook) to capture screenshot with depth.

Hope it helps! If you need any further help, please let me know.

**Comment by NagabhushanSN95** [comment]
Thanks. I wanted to know if it is possible before delving into it. Thanks for the confirmation. I'll try it sometime and update here :)

**Comment by GopiRajuMatta** [comment]
@NagabhushanSN95 & @dadung any update on this? If you've succeeded in extracting depth maps, can you please provide some guidelines to do the same. It would be so helpful!
